export const MAKE_REQ = "MAKE_REQ";

export const GETALLRECORDS_SUCCESS = "GETALLRECORDS_SUCCESS";
export const REQ_FAILED = "REQ_FAILED";

export const CREATE_RECORD_SUCCESS = "CREATE_RECORD_SUCCESS";
export const DELETE_RECORD_SUCCESS = "DELETE_RECORD_SUCCESS";
export const UPDATE_RECORD = "UPDATE_RECORD";

export const SELECT_RECORD = "SELECT_RECORD";